### ISSUE TITLE
reduce logging

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#183]
when I run the coursier sbt plugin, I get a lot of console output regarding resolving. This just fills the screen and will result in hundreds of MB of logs on some of my larger projects.

Can this please be disabled by default, with an option to bring it back? Using `debug` level logs in sbt would probably help a lot.

**Comment by alexarchambault** [comment]
Yep, I'll rework verbosity a bit, along with things about it recently discussed on the Gitter channel...

**Comment by alexarchambault** [comment]
Fixed since https://github.com/alexarchambault/coursier/pull/197. The plugin is much less verbose by default now.

**Comment by fommil** [comment]
I think this still needs some work

**Comment by alexarchambault** [comment]
@fommil Was it actually a red herring (https://github.com/ensime/ensime-server/pull/1312#issuecomment-201559859)?

**Comment by fommil** [comment]
I'm still seeing loads of logging with M10 on my ensime-server branch, hundreds of lines maybe (even after everything is downloaded).

**Comment by alexarchambault** [comment]
What do these look like? I would still expect a bunch of `Downloading https://...` and `Downloaded https://...` lines, but only if the cache is empty.

**Comment by fommil** [comment]
I'll grab you a text file and put it on gist when I'm next at my computer

**Comment by fommil** [comment]
I created a gist with logging with/without coursier (all jars that can be obtained are present locally) https://gist.github.com/fommil/66620a69f51a14f2278f

It's about 2,000 lines (coursier) vs 300-ish (stock sbt). I'd say 300 is already too much, but I guess we can't do much better than that.

`sbt gen-ensime gen-ensime-project`
